# Generated by Django 3.2.7 on 2021-09-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('course_number', models.IntegerField(max_length=10)),
                ('instuctor_name', models.CharField(max_length=30)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
    ]
