# Generated by Django 3.2.7 on 2021-09-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_alter_djangoclasses_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='course_number',
            field=models.CharField(max_length=30),
        ),
    ]
