# Generated by Django 3.2.7 on 2021-09-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0003_alter_djangoclasses_course_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangoclasses',
            old_name='instuctor_name',
            new_name='instructorName',
        ),
    ]
